<?php

namespace Swagger\Client\Enums;

enum VentilationCodesEnum: int
{
    case ZERO_PERCENT = 1;
    case LOW_RATE = 2;
    case MID_RATE = 3;
    case HIGH_RATE = 4;

    case REVERSE_CHARGE_CONTRACTOR = 21;
    case MISC_EXCLUDING_VAT = 22;
    case MARGIN = 24;

    case IC_GOODS = 51;
    case IC_SERVICES = 55;

    case IMPORT_EXPORT = 70;

    case INTERNATIONAL_TRANSPORT_PEOPLE = 101;
    case IMPORT_VIA_EU = 102;
    case OSS = 104;

    /**
     * Default VAT percentage for this ventilation code
     */
    public function defaultVatPercentage(): float
    {
        return match ($this) {
            self::ZERO_PERCENT => 0.00,
            self::LOW_RATE => 6.00,
            self::MID_RATE => 12.00,
            self::HIGH_RATE => 21.00,

            self::REVERSE_CHARGE_CONTRACTOR,
            self::MISC_EXCLUDING_VAT,
            self::MARGIN,
            self::IC_GOODS,
            self::IC_SERVICES,
            self::IMPORT_EXPORT,
            self::INTERNATIONAL_TRANSPORT_PEOPLE,
            self::IMPORT_VIA_EU,
            self::OSS => 0.00,
        };
    }

    /**
     * Peppol UBL TaxCategory ID
     */
    public function peppolTaxCategoryId(): string
    {
        return match ($this) {
            self::ZERO_PERCENT => 'Z',

            self::LOW_RATE,
            self::MID_RATE,
            self::HIGH_RATE => 'S',

            self::REVERSE_CHARGE_CONTRACTOR => 'AE',
            self::MISC_EXCLUDING_VAT => 'O',
            self::MARGIN => 'E',

            self::IC_GOODS,
            self::IC_SERVICES => 'K',

            self::IMPORT_EXPORT => 'G',

            self::INTERNATIONAL_TRANSPORT_PEOPLE,
            self::IMPORT_VIA_EU,
            self::OSS => 'E',
        };
    }

    /**
     * Tax exemption reason text generated by Billit in Peppol UBL (if any)
     */
    public function taxExemptionReason(): ?string
    {
        return match ($this) {
            self::REVERSE_CHARGE_CONTRACTOR => 'Reverse Charge',
            self::MISC_EXCLUDING_VAT => 'Miscellaneous non-VAT',
            self::MARGIN,
            self::INTERNATIONAL_TRANSPORT_PEOPLE,
            self::IMPORT_VIA_EU,
            self::OSS => 'Exempt from VAT',

            self::IC_GOODS,
            self::IC_SERVICES => 'VAT exempt for EEA intra-community supply of goods and services',

            self::IMPORT_EXPORT => 'Free export item, VAT not charged',

            default => null,
        };
    }

    /**
     * Human-readable description
     */
    public function description(): string
    {
        return match ($this) {
            self::ZERO_PERCENT => '0% VAT',
            self::LOW_RATE => 'Low VAT rate',
            self::MID_RATE => 'Mid VAT rate',
            self::HIGH_RATE => 'High VAT rate',

            self::REVERSE_CHARGE_CONTRACTOR => 'VAT reverse charge (contractor)',
            self::MISC_EXCLUDING_VAT => 'Miscellaneous excluding VAT',
            self::MARGIN => 'Margin scheme',

            self::IC_GOODS => 'Intra-community goods',
            self::IC_SERVICES => 'Intra-community services',

            self::IMPORT_EXPORT => 'Import / export',
            self::INTERNATIONAL_TRANSPORT_PEOPLE => 'International transport of people',
            self::IMPORT_VIA_EU => 'Import via EU',
            self::OSS => 'One Stop Shop (OSS)',
        };
    }
}
